MRM.Ibis.VirginRadioTour.GUI.MVC/Controllers/EventController.cs
using AutoMapper;
using MRM.Ibis.VirginRadioTour.Core.BLL;
using MRM.Ibis.VirginRadioTour.GUI.MVC.ViewModels;
using System;
using System.Web.Mvc;

namespace MRM.Ibis.VirginRadioTour.GUI.MVC.Controllers
{
    public class EventController : BaseController
    {
        // GET: Event
        public ActionResult EventDetails(string eventId)
        {
            try
            {
                EventManager manager = new EventManager(UnitOfWork);
                var @event = manager.FindByName(eventId);

                return PartialView("_EventDetails",Mapper.Map<EventViewModel>(@event));
            }
            catch (System.Exception ex)
            {
                throw new Exception(ex.Message);
            }

        }
    }
}

MRM.Ibis.VirginRadioTour.GUI.MVC/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse">
        @**@<div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
                <div class="navbar-collapse collapse">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Accueil", "Index", "Home", null, new { @class = "navbar-brand" })</li>
                            <li>@Html.ActionLink("Gestion des évennements", "Index", "Event", null, new { @class = "navbar-brand" })</li>
                            @*<li><a href="http://www.serviceclient.odr.fr/" target="_blank" class="navbar-brand">Extranet TESSI</a></li>*@
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Déconnexion", "Logout", "Home", null, new { @class = "navbar-brand" })</li>
                        </ul>
                    }
                </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>